const products = [
  {
    id: 1,
    name: "100 Days of Code: The Complete Python Pro Bootcamp",
    teacher: "Dr. Angela Yu, Developer and Lead Instructor",
    rate: 4.7,
    reviews: 334623,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image1.jpg",
  },
  {
    id: 2,
    name: "The Complete 2024 Web Development Bootcamp",
    teacher: "Dr. Angela Yu, Developer and Lead Instructor",
    rate: 4.7,
    reviews: 411920,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image2.jpg",
  },
  {
    id: 3,
    name: "[NEW] Ultimate AWS Certified Cloud Practitioner CLF-C02",
    teacher:
      "Stephane Maarek | AWS Certified Cloud Practitioner,Solutions Architect,Developer",
    rate: 4.7,
    reviews: 226635,
    originalPrice: 10800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image3.jpg",
  },
  {
    id: 4,
    name: "Ultimate AWS Certified Solutions Architect Associate SAA-C03",
    teacher:
      "Stephane Maarek | AWS Certified Cloud Practitioner,Solutions Architect,Developer",
    rate: 4.7,
    reviews: 240220,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image4.jpg",
  },
  {
    id: 5,
    name: "The Complete Python Bootcamp From Zero to Hero in Python",
    teacher: "Jose Portilla, Pierian Training",
    rate: 4.6,
    reviews: 552379,
    originalPrice: 27800,
    currentPrice: 1500,
    bestSell: "Bestseller",
    image: "images/image5.jpg",
  },
  {
    id: 6,
    name: "React - The Complete Guide 2024 (incl. Next.js, Redux)",
    teacher: "Academind by Maximilian Schwarzmüller, Maximilian Schwarzmüller",
    rate: 4.6,
    reviews: 220710,
    originalPrice: 26800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image6.jpg",
  },
  {
    id: 7,
    name: "The Complete JavaScript Course 2024: From Zero to Expert!",
    teacher: "Jonas Schmedtmann",
    rate: 4.7,
    reviews: 215809,
    originalPrice: 27800,
    currentPrice: 1800,
    bestSell: "Bestseller",
    image: "images/image7.jpg",
  },
  {
    id: 8,
    name: "Microsoft Power BI Desktop for Business Intelligence",
    teacher: "Maven Analytics, Chris Dutton, Aaron Parry",
    rate: 4.6,
    reviews: 147113,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image8.jpg",
  },
  {
    id: 9,
    name: "Machine Learning A-Z: AI, Python & R + ChatGPT Prize [2024]",
    teacher:
      "Kirill Eremenko, Hadelin de Ponteves, SuperDataScience Team, Ligency Team",
    rate: 4.5,
    reviews: 191419,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image9.jpg",
  },
  {
    id: 10,
    name: "The Ultimate React Course 2024: React, Next.js, Redux & More",
    teacher: "Jonas Schmedtmann",
    rate: 4.7,
    reviews: 16362,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image10.jpg",
  },
  {
    id: 11,
    name: "The Data Science Course: Complete Data Science Bootcamp 2024",
    teacher: "365 Careers",
    rate: 4.6,
    reviews: 146804,
    originalPrice: 27800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image11.jpg",
  },
  {
    id: 12,
    name: "Complete web development course",
    teacher: "Hitesh Choudhary",
    rate: 4.7,
    reviews: 3605,
    originalPrice: 3000,
    currentPrice: 1300,
    bestSell: "Hot & New",
    image: "images/image12.jpg",
  },
  {
    id: 13,
    name: "PMP Certification Exam Prep Course 35 PDU Contact Hours/PDU",
    teacher: "TIA Education, Andrew Ramdayal",
    rate: 4.7,
    reviews: 105553,
    originalPrice: 12800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image13.jpg",
  },
  {
    id: 14,
    name: "The Complete SQL Bootcamp: Go from Zero to Hero",
    teacher: "Jose Portilla, Pierian Training",
    rate: 4.7,
    reviews: 218786,
    originalPrice: 26800,
    currentPrice: 1300,
    bestSell: "Bestseller",
    image: "images/image14.jpg",
  },
];
